// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchemaDoc.Infrastructure.Data;

#nullable disable

namespace SchemaDoc.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413194326_AddConnectionTags")]
    partial class AddConnectionTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.ColumnAnnotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("TableAnnotationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableAnnotationId", "ColumnName")
                        .IsUnique();

                    b.ToTable("ColumnAnnotations");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.SavedConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDatabaseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagColor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.SchemaSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "DatabaseName");

                    b.ToTable("SchemaSnapshots");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.TableAnnotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionName", "DatabaseName", "SchemaName", "TableName")
                        .IsUnique();

                    b.ToTable("TableAnnotations");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.ColumnAnnotation", b =>
                {
                    b.HasOne("SchemaDoc.Infrastructure.Data.TableAnnotation", "TableAnnotation")
                        .WithMany("ColumnAnnotations")
                        .HasForeignKey("TableAnnotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableAnnotation");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.SchemaSnapshot", b =>
                {
                    b.HasOne("SchemaDoc.Infrastructure.Data.SavedConnection", "Connection")
                        .WithMany("Snapshots")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.SavedConnection", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("SchemaDoc.Infrastructure.Data.TableAnnotation", b =>
                {
                    b.Navigation("ColumnAnnotations");
                });
#pragma warning restore 612, 618
        }
    }
}
