using System.Text;
using System.Web;
using SchemaDoc.Core.Models;

namespace SchemaDoc.Export;

public static class HtmlExporter
{
    public static byte[] GenerateHtml(DatabaseSchema schema, IReadOnlyList<TableAnnotationDto>? annotations = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\"/>");
        sb.AppendLine($"<title>{Esc(schema.DatabaseName)} — Schema Documentation</title>");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>");
        AppendStyles(sb);
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");

        // Header
        sb.AppendLine("<header>");
        sb.AppendLine($"<h1>Schema Documentation</h1>");
        sb.AppendLine($"<h2>{Esc(schema.DatabaseName)}</h2>");
        sb.AppendLine($"<p class=\"meta\">Provider: {schema.Provider} &middot; Generated: {schema.ExtractedAt:MMMM dd, yyyy HH:mm} &middot; {schema.Tables.Count} tables &middot; {schema.Views.Count} views &middot; {schema.ForeignKeys.Count} foreign keys</p>");
        sb.AppendLine("</header>");

        // Filter
        sb.AppendLine("<div class=\"filter-bar\">");
        sb.AppendLine("<input type=\"text\" id=\"tableFilter\" placeholder=\"Filter tables...\" oninput=\"filterTables(this.value)\" />");
        sb.AppendLine("</div>");

        // TOC
        sb.AppendLine("<nav id=\"toc\">");
        sb.AppendLine("<h3>Table of Contents</h3>");
        sb.AppendLine("<ul>");
        foreach (var table in schema.Tables)
        {
            var anchor = Anchor(table.FullName);
            sb.AppendLine($"<li class=\"toc-item\" data-name=\"{Esc(table.FullName).ToLowerInvariant()}\"><a href=\"#{anchor}\">{Esc(table.FullName)}</a> <span class=\"count\">{table.Columns.Count} cols</span></li>");
        }
        sb.AppendLine("</ul>");
        sb.AppendLine("</nav>");

        // Tables
        foreach (var table in schema.Tables)
        {
            var annotation = annotations?.FirstOrDefault(a =>
                a.SchemaName == table.Schema && a.TableName == table.Name);
            AppendTableSection(sb, table, annotation, schema.ForeignKeys);
        }

        // Footer
        sb.AppendLine("<footer>Generated by SchemaDoc</footer>");

        AppendScript(sb);
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    private static void AppendTableSection(StringBuilder sb, SchemaTable table,
        TableAnnotationDto? annotation, IReadOnlyList<ForeignKeyRelation> allFks)
    {
        var anchor = Anchor(table.FullName);
        sb.AppendLine($"<section class=\"table-section\" id=\"{anchor}\" data-name=\"{Esc(table.FullName).ToLowerInvariant()}\">");
        sb.AppendLine($"<h3>{Esc(table.FullName)}</h3>");

        if (table.RowCount.HasValue)
            sb.AppendLine($"<p class=\"meta\">Rows: {table.RowCount.Value:N0}</p>");

        if (!string.IsNullOrWhiteSpace(annotation?.Description))
            sb.AppendLine($"<p class=\"description\">{Esc(annotation.Description)}</p>");

        if (!string.IsNullOrWhiteSpace(annotation?.Tags))
        {
            sb.Append("<div class=\"tags\">");
            foreach (var tag in annotation.Tags.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                sb.Append($"<span class=\"tag\">{Esc(tag)}</span>");
            sb.AppendLine("</div>");
        }

        // Columns grid
        sb.AppendLine("<table>");
        sb.AppendLine("<thead><tr><th>#</th><th>Name</th><th>Type</th><th>Nullable</th><th>PK</th><th>FK</th><th>Description</th></tr></thead>");
        sb.AppendLine("<tbody>");
        var ordinal = 1;
        foreach (var col in table.Columns.OrderBy(c => c.OrdinalPosition))
        {
            var colAnnotation = annotation?.ColumnAnnotations.FirstOrDefault(ca => ca.ColumnName == col.Name);
            var desc = colAnnotation?.Description ?? col.DbNativeComment ?? "";
            var typeText = FormatType(col);
            var rowClass = ordinal % 2 == 0 ? " class=\"alt\"" : "";

            sb.Append($"<tr{rowClass}>");
            sb.Append($"<td>{ordinal}</td>");
            sb.Append($"<td class=\"col-name{(col.IsPrimaryKey ? " pk-name" : "")}\">{Esc(col.Name)}</td>");
            sb.Append($"<td class=\"col-type\">{Esc(typeText)}</td>");
            sb.Append($"<td>{(col.IsNullable ? "Yes" : "No")}</td>");
            sb.Append(col.IsPrimaryKey ? "<td><span class=\"badge pk\">PK</span></td>" : "<td></td>");
            sb.Append(col.IsForeignKey ? "<td><span class=\"badge fk\">FK</span></td>" : "<td></td>");
            sb.Append($"<td class=\"col-desc\">{Esc(desc)}</td>");
            sb.AppendLine("</tr>");
            ordinal++;
        }
        sb.AppendLine("</tbody></table>");

        // FK relationships
        var fks = allFks.Where(fk => fk.ParentSchema == table.Schema && fk.ParentTable == table.Name).ToList();
        if (fks.Count > 0)
        {
            sb.AppendLine("<h4>Foreign Key Relationships</h4>");
            sb.AppendLine("<table class=\"fk-table\">");
            sb.AppendLine("<thead><tr><th>Constraint</th><th>Column</th><th>References</th><th>On Delete</th><th>On Update</th></tr></thead>");
            sb.AppendLine("<tbody>");
            var i = 1;
            foreach (var fk in fks)
            {
                var rc = i % 2 == 0 ? " class=\"alt\"" : "";
                sb.Append($"<tr{rc}>");
                sb.Append($"<td>{Esc(fk.ConstraintName)}</td>");
                sb.Append($"<td>{Esc(fk.ParentColumn)}</td>");
                sb.Append($"<td>{Esc(fk.ReferencedSchema)}.{Esc(fk.ReferencedTable)}.{Esc(fk.ReferencedColumn)}</td>");
                sb.Append($"<td>{Esc(fk.OnDelete ?? "NO ACTION")}</td>");
                sb.Append($"<td>{Esc(fk.OnUpdate ?? "NO ACTION")}</td>");
                sb.AppendLine("</tr>");
                i++;
            }
            sb.AppendLine("</tbody></table>");
        }

        sb.AppendLine("<a href=\"#toc\" class=\"back-top\">Back to top</a>");
        sb.AppendLine("</section>");
    }

    private static string FormatType(SchemaColumn col)
    {
        var t = col.DataType;
        if (!string.IsNullOrEmpty(col.MaxLength) && col.MaxLength != "-1")
            t += $"({col.MaxLength})";
        else if (col.NumericPrecision.HasValue && col.NumericScale.HasValue)
            t += $"({col.NumericPrecision},{col.NumericScale})";
        return t;
    }

    private static string Esc(string s) => HttpUtility.HtmlEncode(s);
    private static string Anchor(string name) => name.Replace(".", "_").Replace(" ", "_");

    private static void AppendStyles(StringBuilder sb)
    {
        sb.AppendLine("<style>");
        sb.AppendLine(@"
:root { --primary: #1E3A5F; --accent: #2563EB; --bg: #fafbfc; --card: #fff; --border: #e2e8f0; --text: #1a202c; --muted: #718096; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 1100px; margin: 0 auto; }
header { text-align: center; padding: 2rem 0 1.5rem; border-bottom: 2px solid var(--accent); margin-bottom: 2rem; }
header h1 { font-size: 2rem; color: var(--primary); margin-bottom: 0.25rem; }
header h2 { font-size: 1.3rem; color: var(--accent); font-weight: 400; margin-bottom: 0.5rem; }
.meta { font-size: 0.8rem; color: var(--muted); }
.filter-bar { margin-bottom: 1.5rem; }
.filter-bar input { width: 100%; padding: 0.5rem 0.75rem; border: 1px solid var(--border); border-radius: 6px; font-size: 0.85rem; }
nav { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; margin-bottom: 2rem; }
nav h3 { font-size: 1.1rem; color: var(--primary); margin-bottom: 0.75rem; }
nav ul { list-style: none; columns: 2; column-gap: 2rem; }
nav li { padding: 0.2rem 0; font-size: 0.82rem; }
nav a { color: var(--accent); text-decoration: none; }
nav a:hover { text-decoration: underline; }
.count { color: var(--muted); font-size: 0.72rem; }
.table-section { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 1.25rem; margin-bottom: 1.25rem; }
.table-section h3 { font-size: 1.15rem; color: var(--primary); margin-bottom: 0.5rem; }
.table-section h4 { font-size: 0.95rem; color: var(--primary); margin: 1rem 0 0.5rem; }
.description { font-style: italic; color: #4a5568; font-size: 0.85rem; margin-bottom: 0.5rem; }
.tags { display: flex; gap: 0.4rem; margin-bottom: 0.75rem; flex-wrap: wrap; }
.tag { background: #eff6ff; color: var(--accent); font-size: 0.72rem; padding: 0.15rem 0.5rem; border-radius: 999px; }
table { width: 100%; border-collapse: collapse; font-size: 0.82rem; margin-top: 0.5rem; }
th { background: var(--primary); color: #fff; text-align: left; padding: 0.4rem 0.6rem; font-size: 0.78rem; font-weight: 600; }
td { padding: 0.35rem 0.6rem; border-bottom: 1px solid var(--border); }
tr.alt td { background: #f7fafc; }
.col-name { font-weight: 500; }
.pk-name { font-weight: 700; }
.col-type { font-family: ui-monospace, 'Courier New', monospace; font-size: 0.78rem; color: #6b46c1; }
.col-desc { color: var(--muted); font-size: 0.78rem; }
.badge { display: inline-block; font-size: 0.68rem; font-weight: 700; padding: 0.1rem 0.4rem; border-radius: 3px; }
.badge.pk { background: #fef3c7; color: #92400e; }
.badge.fk { background: #dbeafe; color: #1e40af; }
.fk-table { margin-top: 0.25rem; }
.back-top { display: inline-block; margin-top: 0.75rem; font-size: 0.75rem; color: var(--accent); text-decoration: none; }
.back-top:hover { text-decoration: underline; }
footer { text-align: center; padding: 2rem 0; color: var(--muted); font-size: 0.78rem; border-top: 1px solid var(--border); margin-top: 2rem; }
@media print { body { padding: 0; } .filter-bar { display: none; } .back-top { display: none; } .table-section { break-inside: avoid; } }
@media (max-width: 640px) { nav ul { columns: 1; } body { padding: 1rem; } }
");
        sb.AppendLine("</style>");
    }

    private static void AppendScript(StringBuilder sb)
    {
        sb.AppendLine("<script>");
        sb.AppendLine(@"
function filterTables(q) {
  q = q.toLowerCase();
  document.querySelectorAll('.table-section').forEach(s => {
    s.style.display = s.dataset.name.includes(q) ? '' : 'none';
  });
  document.querySelectorAll('.toc-item').forEach(li => {
    li.style.display = li.dataset.name.includes(q) ? '' : 'none';
  });
}
");
        sb.AppendLine("</script>");
    }
}
